project: coconut_learnable_full
name: gsm-coconut_learnable_full
save_path: exps/gsm_coconut_learnable_full

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False
latent_variant: learnable_weights

latent_window_size: 4
c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

model_id: openai-community/gpt2
load_model_path: exps/gsm_cot_learnable_full/gsm-cot_learnable_full/checkpoint_5

seed: 0
resume: 5
bf16: false
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True

batch_size_training: 8
debug: False
gradient_accumulation_steps: 4

num_epochs: 25
lr: 1.0e-4
weight_decay: 0.01