project: coconut_learnable_full
name: math-coconut_learnable_full
save_path: exps/math_coconut_learnable_full

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False
latent_variant: learnable_weights

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

model_id: openai-community/gpt2
load_model_path: None

seed: 0
resume: 0
bf16: False
train_path: data/math_train.json
val_path: data/math_valid.json
reset_optimizer: True

batch_size_training: 2
debug: False
gradient_accumulation_steps: 4
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01