project: coconut_learnable_full
name: prontoqa-coconut_learnable_full-eval
save_path: exps/prontoqa_coconut_learnable_full-eval

only_eval: True

coconut: True
cot: False
no_thoughts: False
no_cot: False
latent_variant: learnable_weights

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: exps/prontoqa_coconut_learnable_full/prontoqa-coconut_learnable_full/checkpoint_40
seed: 0
resume: 40
bf16: False
train_path: data/prontoqa_train.json
val_path: data/prontoqa_test.json
reset_optimizer: True

batch_size_training: 4
debug: False
gradient_accumulation_steps: 8
num_epochs: 50
lr: 1.0e-4
weight_decay: 0.01