project: coconut_learnable_full
name: prosqa-coconut_learnable_full
save_path: exps/prosqa_coconut_learnable_full

only_eval: True

coconut: True
cot: False
no_thoughts: False
no_cot: False
latent_variant: learnable_weights

latent_window_size: 4
c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

model_id: openai-community/gpt2
load_model_path: exps/prosqa_coconut_learnable_full/prosqa-coconut_learnable_full/checkpoint_40

seed: 0
resume: 40
bf16: False
train_path: data/prosqa_train.json
val_path: data/prosqa_test.json
reset_optimizer: True

batch_size_training: 4
debug: False
gradient_accumulation_steps: 8
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01