project: coconut_learnable
name: gsm-cot_learnable
save_path: exps/gsm_cot_learnable

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False
latent_variant: learnable_weights

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

model_id: EleutherAI/gpt-neo-1.3B
load_model_path: None

seed: 0
resume: 0
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False

batch_size_training: 4
debug: False
gradient_accumulation_steps: 4

num_epochs: 25
lr: 1.0e-6
weight_decay: 0.01