# Evaluation-only config for Stage 1
project: coconut_learnable
name: gsm-coconut-eval
save_path: exps/gsm8k_coconut_cpu

only_eval: True

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

model_id: openai-community/gpt2
load_model_path: exps/gsm8k_coconut_cpu/gsm-coconut/checkpoint_15

seed: 0
resume: 15
bf16: false
train_path: data/gsm_train.json
val_path: data/gsm_test.json
reset_optimizer: True

batch_size_training: 8
debug: False
gradient_accumulation_steps: 4

num_epochs: 25
lr: 1.0e-4
weight_decay: 0.01
