project: coconut_learnable_lora
name: gsm-coconut_learnable_lora-eval
save_path: exps/gsm_coconut_learnable_lora-eval

only_eval: True

coconut: True
cot: False
no_thoughts: False
no_cot: False
latent_variant: learnable_weights_lora

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

model_id: openai-community/gpt2
load_model_path: exps/gsm_coconut_learnable_lora/gsm-coconut_learnable_lora/checkpoint_21

seed: 0
resume: 21
bf16: false
train_path: data/gsm_train.json
val_path: data/gsm_test.json
reset_optimizer: True

batch_size_training: 1
debug: False
gradient_accumulation_steps: 6

num_epochs: 25
lr: 1.0e-4
weight_decay: 0.01
