project: coconut_learnable_lora
name: prontoqa-coconut_learnable_lora
save_path: exps/prontoqa_coconut_learnable_lora

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False
latent_variant: learnable_weights_lora

c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None

seed: 0
resume: 0
bf16: False
train_path: data/prontoqa_train.json
val_path: data/prontoqa_valid.json
reset_optimizer: True

batch_size_training: 4
debug: False
gradient_accumulation_steps: 8
num_epochs: 50
lr: 1.0e-4
weight_decay: 0.01