project: coconut_learnable_lora
name: prosqa-coconut_learnable_lora
save_path: exps/prosqa_coconut_learnable_lora

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False
latent_variant: learnable_weights_lora

latent_window_size: 4
c_thought: 1
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

model_id: EleutherAI/gpt-neo-1.3B
load_model_path: None

seed: 0
resume: 0
bf16: False
train_path: data/prosqa_train.json
val_path: data/prosqa_valid.json
reset_optimizer: True

batch_size_training: 1
debug: True
gradient_accumulation_steps: 6
num_epochs: 50
lr: !!float "1e-5"
weight_decay: 0.01