# Stage 0: generate reasoning steps without any latent thoughts yet
project: coconut
name: gsm-cot
save_path: exps/gsm8k_cot_cpu

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

save_only_improve: True
uniform_prob: 0.0

model_id: openai-community/gpt2
load_model_path: None

seed: 0
resume: 0
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False

batch_size_training: 8
debug: False
gradient_accumulation_steps: 4

num_epochs: 25
lr: 1.0e-4
# regularization term that penalizes large weights to prevent overfitting
weight_decay: 0.01
