project: coconut_learnable
name: gsm-coconut_basic
save_path: exps/gsm_coconut_basic

only_eval: False

coconut: True
cot: False
no_thoughts: False
no_cot: False
latent_variant: None

latent_window_size: 4
c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0

model_id: EleutherAI/gpt-neo-1.3B
load_model_path: None

seed: 0
resume: 0
bf16: false
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True

batch_size_training: 4
debug: False
gradient_accumulation_steps: 4

num_epochs: 25
lr: 1.0e-4
weight_decay: 0.01